config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'
  resources :studies
  resources :posts
  resources :surveys
  resources :answers
  resources :questions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'welcome', to: 'welcome#index'
  get 'faq', to: 'faq#index'
  get 'studies', to: 'studies#index'
  get 'posts', to: 'posts#index'
  get 'profile', to: 'profiles#index'
  get 'profile/edit', to:'profiles#edit'
  put 'profile/edit', to:'profiles#update'
  get 'welcome/about', to:'welcome#about'
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
	has_many :answers, dependent: :destroy

	validates :subject, length: {  allow_nil: false, :allow_blank => false, message: "can't be empty" }
	validates :content, length: {  allow_nil: false, :allow_blank => false, message: "can't be empty" }

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = []
    @questions2 = []

    Question.all.each do |question|
      if question.is_private == false
        @questions.append(question)
      elsif question.is_private == true or question.user_id == current_user.id 
        @questions2.append(question)
      end
    end
  end

  # GET /questions/1 or /questions/1.json
  def show
    @answer = Answer.new
    
    @answers = []
    Answer.all.each do |answer|
      if answer.question_id == @question.id
        @answers.append(answer)
      end
    end
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit

  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)#

    respond_to do |format|
      if @question.save
        format.html { redirect_to question_url(@question), notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    if !(current_user and (current_user.id == @question.user_id or current_user.role != 0))
     return 
    else
      @question.destroy

      respond_to do |format|
        format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:content, :is_faq, :is_private, :user_id, :subject)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<body class="bg-ques">
  <section class="gradient-form mt-20">
  <div class="container py-5 h-100 ">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-8">
        <div class="card rounded-3">
          <div class="row g-0">
          <div class="col card-body gradient-custom-2 text-white text-center"> 
            <div class="">
                  <%= image_tag "covid2.png" %>
                </div>
                  <h1 class="mt-1 mb-2 pb-1 text-center" style="font-family: 'Acme', sans-serif;">Estebana</h1>
                <p class="small mb-0">Do you have any wonders,questions or fears? Write it down so that our specialists would satisfy you with the answers you deserve.</p>
          </div>
        </div>
          <div class="row g-0">
            <div class="col card-body"> 
                  <%= form_with(model: question) do |form| %>
                    <% if question.errors.any? %>
                      <div class="border border-danger bg-danger m-2" id="error_explanation">
                        <h3 class="pt-2 px-2"><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h3>
                        <ul>
                          <% question.errors.each do |error| %>
                            <li><%= error.full_message %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>
                <h4 class="text-center">Write down your question</h4>
                <div class="form-outline mb-4">
                  <%= form.label :Question_Subject%><br>
                  <%= form.text_field :subject , :class =>"form-control p-2"  %>
                </div>
                <div class="form-outline mb-4">
                  <%= form.label :Question%><br>
                  <%= form.text_area :content , :class =>"form-control p-2"  %>
                </div>
                <% if current_user and current_user.role != 0%>
                  <div class="form-outline mb-4">
                    <%= form.check_box :is_faq %>
                    <%= form.label :Do_you_want_to_list_your_question_as_FAQ?%>
                  </div>
                <% end %>
                <div class="form-outline mb-4">
                  <%= form.check_box :is_private %>
                  <%= form.label :Do_you_want_your_question_to_be_private? %>
                </div>
                <div class="actions">
                  <%= form.hidden_field :user_id, value: current_user.id %>
                </div>
                <div class="actions">
                  <%= form.submit "Submit Question", :class => "btn btn-sign btn-block fa-lg mb-3 form-control" %>
                </div>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</body>

app/views/questions/_form_answer.html.erb
<%= form_with(model: @answer) do |form| %>
  <% if @answer.errors.any? %>
    <div class="border border-danger bg-danger m-2" id="error_explanation">
      <h2 class="pt-2 px-2"><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
      <ul>
        <% @answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p id="notice"><%= notice %></p>
  <div class="field mb-2">
    <h4><strong class="title-color"><%= form.label :Answer_Content %></strong></h4>
    <%= form.text_area :content, :class=>"form-control" %>
  </div>
  <div class="actions">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
   <div class="field">
    <%= form.hidden_field :question_id, value: @question.id %>
  </div>
    <div class="actions text-center mt-3">
      <%= form.submit "Post New Answer", :class => "btn btn-sign mb-3" %>
      <%= link_to 'Edit Question', edit_question_path(@question), :class => "btn btn-sign mb-3" %>
    </div>
<% end %>

app/views/questions/edit.html.erb
<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>
<body class="bg-ques">
  <section class="section container">
    <table class="table table-striped table-hover title-color mt-5 bg-white">
      <thead style="background-color:#223C60;" class="text-white text-center">
        <tr>
          <th>Subject</th>
          <th>Is faq</th>
          <th>Is private</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody class="title-color">
        <% @questions2.each do |question| %>
        <% if current_user and (current_user.role != 0 or question.user_id == current_user.id ) %>
          <tr>
            <td class="text-center title-color"><%= question.subject %></td>
            <td class="text-center title-color"><%= question.is_faq %></td>
            <td class="text-center title-color"><%= question.is_private %></td>
            <td>
              <div class="btn-group " role="group" aria-label="Basic example">
                <%= button_to 'Show ', question, method: :get, :class=>"btn-q btn-secondary" %>
                <% if current_user and (current_user.role != 0 or current_user.id == question.user_id) %>
                  <%= button_to 'Edit ', edit_question_path(question), method: :get, :class=>"btn-q btn-secondary"%>
                  <%= button_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn-q btn-danger" %>
                <% end %>
              </div>
            </td>
          </tr>
        <%end%>
        <%end%>
        <% @questions.each do |question| %>
          <tr>
            <td class="text-center title-color"><%= question.subject %></td>
            <td class="text-center title-color"><%= question.is_faq %></td>
            <td class="text-center title-color"><%= question.is_private %></td>
            <td>
              <div class="btn-group " role="group" aria-label="Basic example">
                <%= button_to 'Show ', question, method: :get, :class=>"btn-q btn-secondary" %>
                <% if current_user and (current_user.role != 0 or current_user.id == question.user_id) %>
                  <%= button_to 'Edit ', edit_question_path(question), method: :get, :class=>"btn-q btn-secondary"%>
                  <%= button_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn-q btn-danger" %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br/>
    <hr/>
    <br/>
    <div class="actions d-flex justify-content-center ">
      <%= link_to 'Have a new question?', new_question_path , :class => "btn btn-sign fa-md mb-3" %>
    </div>
  </section>
</body>

app/views/questions/new.html.erb
<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<body class="bg-ques">
	<section class=" px-10 ">
		<div class="container py-5 h-100 ">
			<div class="row d-flex justify-content-center align-items-center h-100">
				<div class="col-xl-8">
					<div class="card rounded-3">
						<div class="row g-0">
							<div class="col card-body gradient-custom-2 text-white text-center"> 
								<div class="">
									<%= image_tag "covid2.png" %>
								</div>
								<h1 class="mt-1 mb-5 pb-1 text-center" style="font-family: 'Acme', sans-serif;">Question</h1>
							</div>
						</div>
						<div class="row g-0">
							<div class="col card-body"> 
								<div class="form-outline mb-4">
									<h4><strong class="title-color">Subject:</strong></h4>
									<%= @question.subject %>
								</div>
								<hr>
								<div class="form-outline mb-4">
									<h4><strong class="title-color">Content:</strong></h4>
									<%= @question.content %>
								</div>
								<hr>
								<% if current_user and current_user.role != 0 %>
									<%= render 'form_answer', question: @question %>
								<% end %>
								<% @answers.each do |answer| %>
									<div class="border p-2 bg-b container">
										<h4><strong class="p-2 title-color">Author:</strong></h4>
										<p class ="p-2"><%= User.find(answer.user_id).name%></p><hr>
										<h4><strong class="p-2 title-color">Anwsers:</strong></h4>
										<p class ="p-2"><%= answer.content %></p><hr>
										<h4><strong class="p-2 title-color">Created at:</strong></h4>
										<p class ="p-2"><%= answer.created_at %></p>
										<hr>
										<% if current_user and current_user.role != 0 %>
											<%= link_to 'Edit Answer', edit_answer_path(answer), :class => "btn btn-sign mb-3 text-end" %> 
											<%= link_to 'Delete', answer, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-sign mb-3 text-end"  %>
										<% end %>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</body>