config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'
  resources :studies
  resources :posts
  resources :surveys
  resources :answers
  resources :questions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'welcome', to: 'welcome#index'
  get 'faq', to: 'faq#index'
  get 'studies', to: 'studies#index'
  get 'posts', to: 'posts#index'
  get 'profile', to: 'profiles#index'
  get 'profile/edit', to:'profiles#edit'
  put 'profile/edit', to:'profiles#update'
  get 'welcome/about', to:'welcome#about'
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/study.rb
class Study < ApplicationRecord
	validates :title, length: {  allow_nil: false, :allow_blank => false, message: "can't be empty" }
	validates :author, length: {  allow_nil: false, :allow_blank => false, message: "can't be empty" }
	validates :content, length: {  allow_nil: false, :allow_blank => false, message: "can't be empty" }
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: %i[ show edit update destroy ]

  # GET /studies or /studies.json
  def index
    @studies = Study.all
  end

  # GET /studies/1 or /studies/1.json
  def show
  end

  # GET /studies/new
  def new
    if !(current_user and current_user.role != 0)
      redirect_to studies_url(), notice: "You don't have access to add a new study."
    else
      @study = Study.new
    end
  end

  # GET /studies/1/edit
  def edit
    if !(current_user and current_user.role != 0)
      redirect_to studies_url(), notice: "You don't have access to edit this study."
    end
  end

  # POST /studies or /studies.json
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to study_url(@study), notice: "Study was successfully created." }
        format.json { render :show, status: :created, location: @study }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1 or /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to studies_url(@studies), notice: "Study was successfully updated." }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1 or /studies/1.json
  def destroy
    if (current_user and current_user.role == 0) or not current_user
     return 
    else
      @study.destroy

      respond_to do |format|
        format.html { redirect_to studies_url, notice: "Study was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def study_params
      params.require(:study).permit(:study_id ,:content, :author, :title)
    end
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/_form.html.erb
<body class="bg-ques">
  <section class="gradient-form mt-20">
  <div class="container py-5 ">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-xl-8 h-100">
        <div class="card rounded-3">
          <div class="row g-0">
          <div class="col card-body gradient-custom-2 text-white text-center"> 
            <div class="">
              <%= image_tag "covid2.png" %>
            </div>
            <h1 class="mt-1 mb-2 pb-1 text-center" style="font-family: 'Acme', sans-serif;">Estebana</h1>
          </div>
        </div>
          <div class="row g-0">
            <div class="col card-body"> 
                  <%= form_with(model: study) do |form| %>
                    <% if study.errors.any? %>
                      <div class="border border-danger bg-danger m-2" id="error_explanation">
                        <h3 class="pt-2 px-2"><%= pluralize(study.errors.count, "error") %> prohibited this study from being saved:</h3>
                        <ul>
                          <% study.errors.each do |error| %>
                            <li><%= error.full_message %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>
                <h4 class="text-center title-color">Write New Study Details</h4>
                <div class="form-outline mb-4">
                  <h5><strong class="title-color"><%= form.label :title %></strong></h5>
                  <%= form.text_field :title, :class =>"form-control p-2" %>
                </div>
                <div class="form-outline mb-4">
                  <h5><strong class="title-color"><%= form.label :author %></strong></h5>
                  <%= form.text_field :author, :class =>"form-control p-2" %>
                </div>
                <div class="form-outline mb-4">
                  <h5><strong class="title-color"><%= form.label :content %></strong></h5>
                  <%= form.text_area :content, :class =>"form-control p-2" %>
                </div>
                <div class="actions">
                  <%= form.submit "Publish Study", :class => "btn btn-sign btn-block fa-lg mb-3 form-control" %>
                </div>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</body>

app/views/studies/edit.html.erb
<%= render 'form', study: @study %>

app/views/studies/index.html.erb
<body class="bg-ques">
  <section class="section">
    <div class="container ">
      <div class="row d-flex justify-content-center align-items-center">
        <div class="col-xl-12">
          <div class="card rounded-3">
            <div class="row g-0">
              <div class="col card-body gradient-custom-2 text-white text-center"> 
                <div class="">
                  <%= image_tag "covid2.png" %>
                </div>
                <h1 class="mt-1 mb-5 pb-1 text-center" style="font-family: 'Acme', sans-serif;"><strong class="text-lg">Studies</strong></h1>
              </div>
            </div>
            <div class="row g-0">
              <div class="col card-body"> 
               <section>
                <div class="container">
                  <div class="row">
                    <% @studies.each_with_index do |study, index| %>
                      <div class="col-lg-4 d-flex d-inline-block col-md-6 col-sm-6">
                        <div class="service-block mb-5">
                          <%= image_tag("study#{(index%6)+1}.png" , :class => "img-fluid") %>
                          <h3 class="mt-4 mb-2 title-color"><%= study.title %></h3>
                          <h5 class="mt-4 mb-4 title-color"><%= study.author %></h5>
                          <div class="d-flex justify-content-end">
                            <%= link_to 'Show ', study, :class=>"title-color" %> 
                          <% if current_user and (current_user.role != 0 )%>
                            |<%= link_to ' Edit ', edit_study_path(study), :class=>"title-color" %> 
                            |<%= link_to ' Destroy', study, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"title-color" %>
                          <%end%>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
                <% if current_user and current_user.role !=0 %>
                <div class="actions d-flex justify-content-center ">
                  <%= link_to 'Publish new study?', new_study_path , :class => "btn btn-sign fa-md mb-3" %>
                </div>
                <%end%>
              </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>

app/views/studies/new.html.erb
<%= render 'form', study: @study %>

app/views/studies/show.html.erb
<body class="bg-ques">
	<section class=" px-10 ">
		<div class="container py-5 h-100 ">
			<div class="row d-flex justify-content-center align-items-center h-100">
				<div class="col-xl-10">
					<div class="card rounded-3">
						<div class="row g-0">
							<div class="col card-body gradient-custom-2 text-white text-center"> 
								<div class="">
									<%= image_tag "covid2.png" %>
								</div>
								<h1 class="mt-1 mb-5 pb-1 text-center" style="font-family: 'Acme', sans-serif;"><%= @study.title %></h1>
							</div>
						</div>
						<div class="row g-0">
							<div class="row card-body d-flex"> 
								<div class=" form-outline mb-4">
									<h4 ><strong class="title-color">Author:</strong></h4>
									<%= @study.author %>
								</div>
								<hr>
								<div class="form-outline mb-4">
									<h4><strong class="title-color">Content:</strong></h4>
									<%= @study.content %>
								</div>
								
								<div class="text-center">
									<% if current_user and current_user.role != 0 %>
										<hr>	
										<%= link_to 'Edit study', edit_study_path(@study), :class => "btn btn-sign  mb-3" %>
										<%= link_to 'Back', studies_path(@studies), :class => "btn btn-sign  mb-3" %>
									<% end %>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</body>