config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'
  resources :studies
  resources :posts
  resources :surveys
  resources :answers
  resources :questions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'welcome', to: 'welcome#index'
  get 'faq', to: 'faq#index'
  get 'studies', to: 'studies#index'
  get 'posts', to: 'posts#index'
  get 'profile', to: 'profiles#index'
  get 'profile/edit', to:'profiles#edit'
  put 'profile/edit', to:'profiles#update'
  get 'welcome/about', to:'welcome#about'
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/survey.rb
class Survey < ApplicationRecord
	belongs_to :user
	validates :fever_chills, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}
	validates :cough, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}
	validates :difficulty_breathing, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}
	validates :fatigue, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}
	validates :body_ache, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}
	validates :headache, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}
	validates :sensory_loss, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}
	validates :sore_throat, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}
	validates :nausea, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}
	validates :diarrhea, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy ]

  # GET /surveys or /surveys.json
  def index
    @surveys = []

    #needs to be fixed to only send surveys that belongs to a one patient at a time
    Survey.all.each do |survey|
      if survey.user_id 
        @surveys.append(survey)
      end
    end

  end

  # GET /surveys/1 or /surveys/1.json
  def show

  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
    if !(current_user and current_user.role == 2)
      redirect_to survey_url(@survey), notice: "You don't have access to edit this survey."
    end
  end

  # POST /surveys or /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        current_user.medical_state = current_user.calculate_medical_state()
        current_user.save
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully created." }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully updated." }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1 or /surveys/1.json
  def destroy
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:user_id, :fever_chills, :cough, :difficulty_breathing, :fatigue, :body_ache, :headache, :sensory_loss, :sore_throat, :nausea, :diarrhea, :comment)
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<body class="bg-ques">
  <div class="mx-0 container mt-20 px-10 mx-sm-auto">
    <div class="card">
      <div class="card-header" style="background-color:#223C60;">
        <h2 class="card-title text-center text-white mt-2" id="exampleModalLabel">New Survey</h2>
      </div>
      <div class="modal-body">
        <div class="text-center">
          <i class="far fa-file-alt fa-4x mb-3 text-primary"></i>
          <h4>
            <strong class="title-color">Fill In Your Symptoms:</strong>
          </h4>
        </div>
        <hr />
        <%= form_with(model: survey) do |form| %>
          <% if survey.errors.any? %>
            <div class="border border-danger bg-danger m-2"  id="error_explanation">
              <h2 class="pt-2 px-2"><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>
              <ul>
                <% survey.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

        <% p  = {" I strongly do not relate" => 5, " I rarely ralate" => 4, " I sometimes relate" => 3, " I usually relate" => 2, " I always relate" => 1}%>
        <div class="actions">
          <%= form.hidden_field :user_id, value: current_user.id %>
        </div>
        <p><strong class="px-3 title-color"><%= form.label "Do you feel feverish, have flu-like chills, or a fever with an oral temperature of 38°C or higher?" %></strong></p>
        <div class="form-check title-color mb-2">
          <% p.each do |key, value| %>
            <%= form.radio_button :fever_chills, value %><%= key %> <br/>
          <% end %>
        </div>
        <hr />
        <p><strong class="px-3 title-color"><%= form.label "Do you have a cough or has a chronic cough gotten worse recently?"%></strong></p>
        <div class="form-check title-color mb-2">
          <% p.each do |key, value| %>
            <%= form.radio_button :cough, value %><%= key %> <br/>
          <% end %>
        </div>
        <hr />
        <p><strong class="px-3 title-color"><%= form.label "Are you experiencing trouble breathing or shortness of breath?" %></strong></p>
        <div class="form-check title-color mb-2">
          <% p.each do |key, value| %>
            <%= form.radio_button :difficulty_breathing, value %><%= key %> <br/>
          <% end %>
        </div>
        <hr />
        <p><strong class="px-3 title-color"><%= form.label "Do you feel an unusually intense fatigue for no obvious reason?" %></strong></p>
        <div class="form-check title-color mb-2">
          <% p.each do |key, value| %>
            <%= form.radio_button :fatigue, value %><%= key %> <br/>
          <% end %>
        </div>
        <hr />
        <p><strong class="px-3 title-color"><%= form.label "Do you have unusual headache for no specific reason?" %></strong></p>
        <div class="form-check title-color mb-2">
          <% p.each do |key, value| %>
            <%= form.radio_button :headache, value %><%= key %> <br/>
          <% end %>
        </div>
        <hr />
        <p><strong class="px-3 title-color"><%= form.label "Have you had a sudden loss of smell and loss of taste?" %></strong></p>
        <div class="form-check title-color mb-2">
          <% p.each do |key, value| %>
            <%= form.radio_button :sensory_loss, value %><%= key %> <br/>
          <% end %>        </div>
        <hr />
        <p><strong class="px-3 title-color"><%= form.label "Do you have a sore throat?" %></strong></p>
        <div class="form-check title-color mb-2">
          <% p.each do |key, value| %>
            <%= form.radio_button :sore_throat, value %><%= key %> <br/>
          <% end %>
        </div>
        <hr />
        <p><strong class="px-3 title-color"><%= form.label "do you suffer from nausea of an unknown cause?" %></strong></p>
        <div class="form-check title-color mb-2">
          <% p.each do |key, value| %>
            <%= form.radio_button :nausea, value %><%= key %> <br/>
          <% end %>
        </div>
        <hr />
        <p><strong class="px-3 title-color"> <%= form.label "Do you suffer from unusual unstability in your digestive system, such as diarrhea?" %></strong></p>
        <div class="form-check title-color mb-2">
          <% p.each do |key, value| %>
            <%= form.radio_button :diarrhea, value %><%= key %> <br/>
          <% end %>
        </div>
        <hr />
        <p><strong class="px-3 title-color"> <%= form.label "Do you have unusual or unexplained muscle pain, or stiffness (not related to physical activity)?" %></strong></p>
        <div class="form-check title-color mb-2">
          <% p.each do |key, value| %>
            <%= form.radio_button :body_ache, value %><%= key %> <br/>
          <% end %>
        </div>
        <hr />
        <div class="form-outline mb-4">
          <h5 class="text-center"><strong><%= form.label :Do_you_have_any_comments?, :class=>"mb-0 title-color"%></strong></h5>
          <%= form.text_area :comment, :class =>"form-control title-color" %>
        </div>
        <div class="card-footer text-center">
          <%= form.submit "Send Survey", :class => "btn btn-sign px-5 fa-lg mb-3" %>
        </div>
        <%end%>
      </div>
    </div>
  </div>
</body>

app/views/surveys/edit.html.erb
<%= render 'form', survey: @survey %>

app/views/surveys/index.html.erb
<%if current_user and current_user.role !=0 %>
  <body class="bg-ques">
    <section class="section container">
      <table class="table table-striped table-hover title-color mt-5 bg-white">
        <thead style="background-color:#223C60;" class="text-white text-center">
          <tr>
            <th>Survey Date</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody class="title-color">
          <% @surveys.each do |survey| %>
            <tr>
              <td> This survey was filled in: <%= survey.created_at %></td>
              <td>
                <div class="btn-group " role="group" aria-label="Basic example">
                <%= button_to 'Show', survey, method: :get, :class=>"btn-q btn-secondary" %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br/>
      <hr/>
      <br/>
    </section>
  </body>
<%else%>
<% end %>

app/views/surveys/new.html.erb
<%= render 'form', survey: @survey %>

app/views/surveys/show.html.erb
<% p  = {5 =>"I strongly do not relate", 4 => "I rarely ralate", 3 => "I sometimes relate", 2 => "I usually relate", 1 => "I always relate"}%>
<body class="bg-ques">
  <div class="mx-0 container mt-20 px-10 mx-sm-auto">
    <div class="card">
      <div class="card-header" style="background-color:#223C60;">
        <h2 class="card-title text-center text-white mt-2">New Survey</h2>
      </div>
      <div class="modal-body">
        <div class="text-center">
          <i class="far fa-file-alt fa-4x mb-3 text-primary"></i>
          <h4>
            <strong class="title-color">Your Survey From : <%= @survey.created_at %></strong>
          </h4>
        </div>
        <hr />
        <p><strong class="px-3 title-color">Do you feel feverish, have flu-like chills, or a fever with an oral temperature of 38°C or higher?</strong></p>
        <div class="form-check title-color mb-2">
         <%= p[ @survey.fever_chills ] %>
        </div>
        <hr />
        <p><strong class="px-3 title-color">Do you have a cough or has a chronic cough gotten worse recently?, how much can you rete your case?</strong></p>
        <div class="form-check title-color mb-2">
          <%= p[@survey.cough] %>
        </div>
        <hr />
        <p><strong class="px-3 title-color">Are you experiencing trouble breathing or shortness of breath?, how much can you rete your case?</strong></p>
        <div class="form-check title-color mb-2">
          <%= p[@survey.difficulty_breathing] %>
        </div>
        <hr />
        <p><strong class="px-3 title-color">Do you feel an unusually intense fatigue for no obvious reason? how much can you rete your case?</strong></p>
        <div class="form-check title-color mb-2">
          <%= p[@survey.fatigue] %>
        </div>
        <hr />
        <p><strong class="px-3 title-color">Do you have unusual headache for no specific reason?, how much can you rete your case?</strong></p>
        <div class="form-check title-color mb-2">
          <%= p[@survey.headache] %>
        </div>
        <hr />
        <p><strong class="px-3 title-color">Have you had a sudden loss of smell and loss of taste?, how much can you rete your case?</strong></p>
        <div class="form-check title-color mb-2">
          <%= p[@survey.sensory_loss] %>
        </div>
        <hr />
        <p><strong class="px-3 title-color">Do you have a sore throat?, how much can you rete your case?</strong></p>
        <div class="form-check title-color mb-2">
          <%= p[@survey.sore_throat] %>
        </div>
        <hr />
        <p><strong class="px-3 title-color">do you suffer from nausea of an unknown cause?, how much can you rete your case?</strong></p>
        <div class="form-check title-color mb-2">
          <%= p[@survey.nausea] %>
        </div>
        <hr />
        <p><strong class="px-3 title-color">Do you suffer from unusual unstability in your digestive system eg.diarrhea?, how much can you rete your case?</strong></p>
        <div class="form-check title-color mb-2">
          <%= p[@survey.diarrhea] %>
        </div>
        <hr />
        <p><strong class="px-3 title-color">Do you have unusual or unexplained muscle pain, or stiffness (not related to physical activity)?, how much can you rete your case?</strong></p>
        <div class="form-check title-color mb-2">
          <%= p[@survey.body_ache] %>
        </div>
        <hr />
        <div class="form-outline mb-4">
          <h5 class="text-center "><strong class="mb-0 title-color">Your comment:</strong></h5>
          <div class="title-color text-center" >
            <%= @survey.comment%>
          </div>
            
        </div>
        <div class="card-footer text-center">
          <%= link_to 'Back', profile_path(@profile), :class => "btn btn-sign  mb-3" %>
        </div>
      </div>
    </div>
  </div>
</body>